[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Akeem King", email = "akeemtlking@gmail.com"},
]
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.23.2",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}

